language: node_js

node_js:
  - 0.10.25

install:
  - npm install -g karma karma-cli grunt-cli codeclimate-test-reporter
  - npm install

script:
  - npm test

after_script:
  - CODECLIMATE_REPO_TOKEN=155c1e0e145132eb6cf11fe6398f8e4783c2261cb2bc46976853c84135f2cc51 codeclimate < coverage/report-lcov/lcov.info